// Vite plugin for wombat.shader.
//
// Convention: a file named `*.shader.ts` (or `*.shader.tsx`) exports
// a default object describing a shader effect — its source string,
// entry-point requests, target, and (optional) extra ValueDefs.
// The plugin compiles it at build time via the runtime's
// `compileShaderSource` and replaces the module's exports with a
// frozen `CompiledEffect` — including the full `ProgramInterface`.
//
// In dev: each save re-runs the compile. In production: the result
// is inlined into the bundle, so the browser never sees the TS
// Compiler API.
//
// Usage:
//
//   // my-effect.shader.ts
//   import type { ShaderModuleConfig } from "@aardworx/wombat.shader-vite";
//   const config: ShaderModuleConfig = {
//     source: `function vsMain(...) {...}`,
//     entries: [...],
//     target: "glsl",
//     extraValues: [...],
//   };
//   export default config;
//
//   // app.ts
//   import effect from "./my-effect.shader.js";
//   // effect: CompiledEffect (precomputed)

import * as path from "node:path";
import * as fs from "node:fs/promises";
import { compileShaderSource, type CompiledEffect, type CompileOptions } from "@aardworx/wombat.shader";
import type { EntryRequest } from "@aardworx/wombat.shader/frontend";
import type { ValueDef } from "@aardworx/wombat.shader/ir";
import { transformInlineShaders } from "./inline.js";
import { TypeResolver } from "./typeResolver.js";

export { transformInlineShaders } from "./inline.js";
export { TypeResolver } from "./typeResolver.js";

export interface ShaderModuleConfig extends CompileOptions {
  readonly source: string;
  readonly entries: readonly EntryRequest[];
  readonly extraValues?: readonly ValueDef[];
}

export interface PluginOptions {
  /** File pattern to match. Defaults to `**\/*.shader.{ts,tsx,js,mjs}`. */
  readonly include?: RegExp;
  /** Force a different match pattern; overrides `include`. */
  readonly match?: (id: string) => boolean;
  /**
   * Project root for the inline-shader type resolver. Defaults to
   * `process.cwd()`. The resolver discovers `tsconfig.json` from this
   * directory upwards, builds a `ts.LanguageService`, and uses it to
   * resolve closure-capture types and ambient `declare const u: { … }`
   * uniform declarations across the entire project.
   */
  readonly rootDir?: string;
  /** Explicit tsconfig path; auto-discovered from `rootDir` otherwise. */
  readonly tsconfigPath?: string;
}

interface VitePlugin {
  name: string;
  enforce?: "pre" | "post";
  load?(id: string): Promise<{ code: string } | null> | { code: string } | null;
  transform?(code: string, id: string): Promise<{ code: string; map?: null } | null> | { code: string; map?: null } | null;
  handleHotUpdate?(ctx: { file: string; server: { ws: { send(payload: { type: string; path: string }): void } } }): void;
}

const DEFAULT_INCLUDE = /\.shader\.(?:ts|tsx|mjs|js)$/;

export function wombatShader(options: PluginOptions = {}): VitePlugin {
  const matches = options.match ?? ((id: string) => (options.include ?? DEFAULT_INCLUDE).test(id));

  let resolver: TypeResolver | undefined;
  function getResolver(): TypeResolver {
    if (!resolver) {
      resolver = new TypeResolver({
        rootDir: options.rootDir ?? process.cwd(),
        ...(options.tsconfigPath ? { tsconfigPath: options.tsconfigPath } : {}),
      });
    }
    return resolver;
  }

  return {
    name: "wombat-shader",
    enforce: "pre",

    async load(id: string): Promise<{ code: string } | null> {
      const cleanId = id.split("?")[0]!;
      if (!matches(cleanId)) return null;

      // Resolve the user module to extract its default-exported config.
      // We do this by importing the user module via a child Node process
      // — but for simplicity here we use a lightweight inline-eval path:
      // read the file, dynamic-import via `data:` URL, get default export.
      const absPath = path.resolve(cleanId);
      const config = await loadConfig(absPath);
      const compiled = compileShaderSource(
        config.source,
        config.entries,
        {
          target: config.target,
          ...(config.skipOptimisations ? { skipOptimisations: true } : {}),
          ...(config.extraValues ? { extraValues: config.extraValues } : {}),
        },
      );

      // Emit a JS module exporting the precomputed CompiledEffect.
      const json = serialiseEffect(compiled);
      return {
        code: `// Auto-generated by @aardworx/wombat.shader-vite. Do not edit.\n` +
              `const effect = ${json};\n` +
              `export default effect;\n`,
      };
    },

    transform(code: string, id: string) {
      const cleanId = id.split("?")[0]!;
      // The `load` hook above handles `*.shader.ts`. Skip those here
      // so we don't process them twice.
      if (matches(cleanId)) return null;
      // Limit inline-shader scanning to TS / TSX user code.
      if (!/\.(ts|tsx)$/.test(cleanId)) return null;
      // Skip node_modules to avoid scanning third-party deps.
      if (/[\\/]node_modules[\\/]/.test(cleanId)) return null;
      const result = transformInlineShaders(code, cleanId, getResolver());
      if (!result) return null;
      return { code: result.code, map: result.map as null };
    },

    handleHotUpdate(ctx) {
      if (matches(ctx.file)) {
        ctx.server.ws.send({ type: "full-reload", path: "*" });
      }
    },
  };
}

// ─── Helpers ─────────────────────────────────────────────────────────

async function loadConfig(absPath: string): Promise<ShaderModuleConfig> {
  // Read the source as text; if it's a TS file, transpile via tsc API
  // is heavy. The pragmatic approach: load via dynamic import. Vite
  // hands TS files to us already-transformed when they're in node-land,
  // but our `load` runs before any transform. We compile to JS in
  // memory using the TypeScript module the runtime already depends on.
  const src = await fs.readFile(absPath, "utf8");
  const ts = await import("typescript");
  const transpiled = ts.transpileModule(src, {
    compilerOptions: {
      module: ts.ModuleKind.ESNext,
      target: ts.ScriptTarget.ES2022,
      moduleResolution: ts.ModuleResolutionKind.Bundler,
      esModuleInterop: true,
      skipLibCheck: true,
    },
  }).outputText;

  const dataUrl = `data:text/javascript;base64,${Buffer.from(transpiled).toString("base64")}`;
  const mod = await import(dataUrl);
  if (!mod.default) {
    throw new Error(`wombat.shader-vite: ${absPath} has no default export`);
  }
  return mod.default as ShaderModuleConfig;
}

function serialiseEffect(effect: CompiledEffect): string {
  // The interface contains IR Type objects, which serialise fine.
  // IntrinsicRef objects on CallIntrinsic nodes contain functions,
  // but those are only on Expr nodes embedded in the per-stage source
  // — we don't ship the IR at runtime. So a plain JSON.stringify of
  // the public fields works.
  const { target, stages, interface: iface } = effect;
  return JSON.stringify({
    target,
    stages: stages.map((s) => ({
      stage: s.stage,
      entryName: s.entryName,
      source: s.source,
      bindings: s.bindings,
      meta: s.meta,
    })),
    interface: iface,
  }, null, 2);
}
